name: OpenSSH Bastion Docker Image Publishing

on:
  release:
    types: [published]

env:
  IMAGE_NAME: gnzsnz/bastion

jobs:
  publish:
    name: Build and test OpenSSH Bastion
    strategy:
      matrix:
        image_os: [focal, jammy]

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get enviroment variables
        run: |
          grep -v '#' .env-dist | grep '=' > .env
          while IFS= read -r line; do
            echo $line >> $GITHUB_ENV ;
          done < .env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get enviroment variables
        run: |
          grep -v '#' .env-dist | grep '=' > .env
          while IFS= read -r line; do
            echo $line >> $GITHUB_ENV ;
          done < .env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Bastion
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            BASE_VERSION=${env.BASE_VERSION}
            IMAGE_VERSION=${env.IMAGE_VERSION}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}-${{ matrix.image_os }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}-${{ matrix.image_os }}
