name: OpenSSH Bastion Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  USER: bastion
  IMAGE_NAME: gnzsnz/bastion
  SERVER_PORT: 2022

jobs:
  buildntest:
    name: Build and test OpenSSH Bastion
    strategy:
      matrix:
        image_os: [noble, jammy] # bastion docker image OS
        runner_os: [24.04, 22.04] # CI runner
        server_os: [noble, jammy] # server&client OS

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Get enviroment variables
        run: |
          grep -v '#' .env-dist | grep '=' > .env
          while IFS= read -r line; do
            echo $line >> $GITHUB_ENV ;
          done < .env
          echo "SERVER_OS=${{ matrix.server_os }}" >> $GITHUB_ENV
          echo "IMAGE_OS=${{ matrix.image_os }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build OpenSSH Bastion Docker image
        uses: docker/build-push-action@v7
        with:
          push: false
          load: true
          context: .
          build-args: |
            BASE_VERSION=${{ env.BASE_VERSION }}
            IMAGE_VERSION=${{ env.IMAGE_VERSION }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}-${{ matrix.image_os }}

      - name: Build server and client test image
        uses: docker/build-push-action@v7
        with:
          push: false
          load: true
          context: test/
          file: test/Dockerfile
          build-args: |
            BASE_VERSION=${{ env.BASE_VERSION }}
          tags: gnzsnz/openssh:${{ env.IMAGE_VERSION }}-${{ matrix.server_os }}

      - name: Install dependencies
        run: |
          pip3 install -r test/requirements.txt

      - name: Run tests
        run: |
          cd test/
          invoke --no-dedupe run-all
